package join_patterns.code_generation

import join_patterns.types.*
import join_patterns.util.*

import scala.quoted.{Expr, Quotes, Type, Varargs}

/** Creates a lambda that extracts field values from a message into a `LookupEnv`.
  *
  * Accesses case class fields via synthetic `_1`, `_2`, etc. member symbols
  * generated by the compiler for product types.
  *
  * @param outerType
  *   the message type representation.
  * @param varNames
  *   the field names to extract.
  * @return
  *   a `Block` containing the extractor lambda.
  */
private[code_generation] def generateExtractor(using
    quotes: Quotes
)(outerType: quotes.reflect.TypeRepr, varNames: List[String]): quotes.reflect.Block =
  import quotes.reflect.*

  Lambda(
    owner = Symbol.spliceOwner,
    tpe = MethodType(List(""))(_ => List(outerType), _ => TypeRepr.of[LookupEnv]),
    rhsFn = (_: Symbol, params: List[Tree]) =>
      val p0 = params match
        case (id: Ident) :: _ => id
        case _ =>
          report.errorAndAbort("Internal macro error: generateExtractor expected at least one Ident parameter")
      val isMemberName: Symbol => Boolean =
        (p: Symbol) => p.name.head == '_' && p.name.tail.toIntOption.isDefined
      val memberSymbols: List[Symbol] = outerType.typeSymbol.methodMembers
        .filter(isMemberName(_))
        .sortBy(_.name)
      val args = varNames.zipWithIndex.map { (name, i) =>
        Expr.ofTuple(Expr(name), Select(p0, memberSymbols(i)).asExprOf[Any])
      }
      ('{ LookupEnv(${ Varargs[(String, Any)](args) }*) }).asTerm
  )

/** Substitutes all occurrences of an identifier in a term with a replacement expression.
  *
  * @param rhs
  *   the term to transform.
  * @param identToBeReplaced
  *   the name of the identifier to replace.
  * @param replacementExpr
  *   the replacement term.
  * @param sym
  *   the owning symbol for ownership transfer.
  * @return
  *   the transformed term.
  */
private[code_generation] def substitute(using quotes: Quotes)(
    rhs: quotes.reflect.Term,
    identToBeReplaced: String,
    replacementExpr: quotes.reflect.Term
)(sym: quotes.reflect.Symbol): quotes.reflect.Term =
  import quotes.reflect.*

  val transform = new TreeMap:
    override def transformTerm(term: Term)(owner: Symbol): Term =
      term match
        case t: Ident if identToBeReplaced == t.name =>
          replacementExpr.changeOwner(owner)
        case x =>
          super.transformTerm(x)(owner)

  transform.transformTerm(rhs.changeOwner(sym))(sym)

/** Collects all `Ident` (variable) names used inside a term. */
private[code_generation] def getAllVariableNames(using quotes: Quotes)(
    term: quotes.reflect.Term
): List[String] =
  import quotes.reflect.*

  val folder = new TreeAccumulator[List[String]]:
    override def foldTree(acc: List[String], tree: Tree)(owner: Symbol): List[String] =
      tree match
        case Ident(name) => name :: acc
        case e           => foldOverTree(acc, e)(owner)

  folder.foldTree(List(), term)(Symbol.spliceOwner)

/** Replaces bound variable references in an expression with `LookupEnv` lookups,
  * casting each to the original type.
  */
private[code_generation] def replaceInnersWithLookupEnv[T](using quotes: Quotes, tt: Type[T])(
    exp: Expr[T],
    fieldBindingsWithTypes: List[(String, Type[?])],
    lookupEnvExpr: Expr[LookupEnv]
): Expr[T] =
  import quotes.reflect.*

  val transform = new TreeMap:
    override def transformTerm(term: Term)(owner: Symbol): Term =
      term match
        case Ident(n) if fieldBindingsWithTypes.exists(_._1 == n) =>
          val inner = '{ (${ lookupEnvExpr })(${ Expr(n) }) }
          fieldBindingsWithTypes.find(_._1 == n).map(_._2) match
            case Some(tpe) => tpe match
              case '[innerType] => ('{ ${ inner }.asInstanceOf[innerType] }).asTerm
            case None =>
              report.errorAndAbort(s"Internal macro error: variable '$n' not found in pattern bindings")
        case x =>
          super.transformTerm(x)(owner)

  transform.transformTerm(exp.asTerm)(Symbol.spliceOwner).asExprOf[T]
