package join_patterns.code_generation

import join_patterns.types.*
import join_patterns.util.*

import scala.quoted.{Expr, Quotes, Type, Varargs}

/** Creates a lambda that extracts field values from a message into a `LookupEnv`.
  *
  * Accesses case class fields via synthetic `_1`, `_2`, etc. member symbols
  * generated by the compiler for product types.
  *
  * @param outerType
  *   the message type representation.
  * @param varNames
  *   the field names to extract.
  * @return
  *   a `Block` containing the extractor lambda.
  */
private[code_generation] def generateExtractor(using
    quotes: Quotes
)(outerType: quotes.reflect.TypeRepr, varNames: List[String]): quotes.reflect.Block =
  import quotes.reflect.*

  Lambda(
    owner = Symbol.spliceOwner,
    tpe = MethodType(List(""))(_ => List(outerType), _ => TypeRepr.of[LookupEnv]),
    rhsFn = (_: Symbol, params: List[Tree]) =>
      val p0 = params match
        case (id: Ident) :: _ => id
        case _ =>
          report.errorAndAbort("Internal macro error: generateExtractor expected at least one Ident parameter")
      // Look the accessors up by exact name: sorting `_1, _2, ...` as strings would put `_10`
      // before `_2`.
      val accessors: Map[String, Symbol] =
        outerType.typeSymbol.methodMembers.map(m => m.name -> m).toMap
      val args = varNames.zipWithIndex.map { (name, i) =>
        val accessor = accessors.getOrElse(
          s"_${i + 1}",
          report.errorAndAbort(
            s"Cannot bind field ${i + 1} of `${outerType.show}`: it has no `_${i + 1}` accessor. " +
              s"Join patterns can only destructure case classes with as many fields as sub-patterns."
          )
        )
        Expr.ofTuple(Expr(name), Select(p0, accessor).asExprOf[Any])
      }
      ('{ LookupEnv(${ Varargs[(String, Any)](args) }*) }).asTerm
  )

/** Builds the expression that reads the pattern variable `name` from a `LookupEnv`, cast to the
  * type of the field it is bound to.
  */
private[code_generation] def lookupBinding(using quotes: Quotes)(
    lookupEnv: Expr[LookupEnv],
    name: String,
    tpe: quotes.reflect.TypeRepr
): quotes.reflect.Term =
  import quotes.reflect.*

  val inner = '{ ${ lookupEnv }(${ Expr(name) }) }
  tpe.asType match
    case '[innerType] => ('{ ${ inner }.asInstanceOf[innerType] }).asTerm

/** Collects the names of the pattern variables that a term refers to.
  *
  * References are identified by the symbol of the pattern variable's `Bind`, not by name, so a
  * local `val`, `def`, lambda parameter or nested pattern variable that merely has the same name
  * is not mistaken for the pattern variable.
  */
private[code_generation] def getReferencedBindings(using quotes: Quotes)(
    term: quotes.reflect.Term,
    bindings: List[(String, quotes.reflect.Symbol, quotes.reflect.TypeRepr)]
): List[String] =
  import quotes.reflect.*

  val nameOf: Map[Symbol, String] = bindings.map((name, sym, _) => sym -> name).toMap

  val folder = new TreeAccumulator[List[String]]:
    override def foldTree(acc: List[String], tree: Tree)(owner: Symbol): List[String] =
      tree match
        case id: Ident if nameOf.contains(id.symbol) => nameOf(id.symbol) :: acc
        case e                                       => foldOverTree(acc, e)(owner)

  folder.foldTree(List(), term)(Symbol.spliceOwner).distinct

/** Creates a guard lambda `LookupEnv => Boolean` from a guard expression, replacing references to
  * pattern variables with `LookupEnv` lookups, cast to the type of their field.
  *
  * Only identifiers that refer to the pattern variable's own symbol are replaced (see
  * [[getReferencedBindings]]).
  */
private[code_generation] def generateGuardLambda(using quotes: Quotes)(
    exp: Expr[Boolean],
    bindings: List[(String, quotes.reflect.Symbol, quotes.reflect.TypeRepr)]
): Expr[LookupEnv => Boolean] =
  import quotes.reflect.*

  val bySymbol: Map[Symbol, (String, TypeRepr)] =
    bindings.map((name, sym, tpe) => sym -> (name, tpe)).toMap

  Lambda(
    owner = Symbol.spliceOwner,
    tpe = MethodType(List("lookupEnv"))(_ => List(TypeRepr.of[LookupEnv]), _ => TypeRepr.of[Boolean]),
    rhsFn = (sym: Symbol, params: List[Tree]) =>
      val lookupEnvExpr = params match
        case (id: Ident) :: _ => id.asExprOf[LookupEnv]
        case _ =>
          report.errorAndAbort("Internal macro error: generateGuardLambda expected a LookupEnv parameter")
      val transform = new TreeMap:
        override def transformTerm(term: Term)(owner: Symbol): Term =
          term match
            case id: Ident if bySymbol.contains(id.symbol) =>
              val (name, tpe) = bySymbol(id.symbol)
              lookupBinding(lookupEnvExpr, name, tpe)
            case x =>
              super.transformTerm(x)(owner)

      transform.transformTerm(exp.asTerm.changeOwner(sym))(sym)
  ).asExprOf[LookupEnv => Boolean]
